E-Commerce-Portal/E-Commerce-Portal/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Portal.Models
{
    public class Cart
    {
        [Key]
        public int CartId { get; set; }
        [Required]
        public int CustomerId { get; set; }
        [Required]
        public int ProductId { get; set; }
        [Required]
        [RegularExpression(@"^(?!00000)[0-9]{6,6}$", ErrorMessage = "Zipcode is not valid")]
        public int Zipcode { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive number allowed")]
        public int Quantity { get; set; }
        public DateTime DeliveryDate { get; set; }
        public int VendorId { get; set; }

    }
}

E-Commerce-Portal/E-Commerce-Portal/Controllers/CartController.cs
using E_Commerce_Portal.Models;
using E_Commerce_Portal.Services;
using E_Commerce_Portal.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Portal.Controllers
{
    public class CartController : Controller
    {
        private readonly IRepository repo;
        private readonly ILogger<CartController> _logger;
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ECommerceController));


        public CartController(ILogger<CartController> logger, IRepository _repo)
        {
            
            repo = _repo;
            _logger = logger;
            _log4net.Info("Logger in Cart");
        }

 
        // cart page
        
        public ActionResult Index()
        {
            string token = HttpContext.Session.GetString("token");
            
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            int userid = (int)HttpContext.Session.GetInt32("userid");

            List<ProductListView> mymodel = new List<ProductListView>();
            int sum = 0;

            

            foreach(var item in repo.GetCarts(token,userid))
            {
                Product product = repo.GetProducts(token).SingleOrDefault(z => z.Id == item.ProductId);
                sum += product.Price * item.Quantity;
                mymodel.Add(
                    new ProductListView()
                    {
                        CartId = item.CartId,
                        Product = product,
                        Vendor = repo.GetVendors(token).SingleOrDefault(z => z.Id == item.VendorId),
                        Quantity = item.Quantity,
                        AddedDate = item.DeliveryDate,
                        TotalAmount = product.Price * item.Quantity
                    }
               );
            }
            _log4net.Info("User is viewing cart");
            ViewBag.GrandTotal = sum;


            return View(mymodel);
        }

        // add cart form
        public ActionResult AddToCart(int Id)
        {
            if (HttpContext.Session.GetString("token") == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            

            ViewData["ProductId"] = Id;
            ViewData["CustomerId"] = HttpContext.Session.GetInt32("userid");
            ViewData["DeliveryDate1"] = DateTime.Today.AddDays(2);
            ViewData["DeliveryDate2"] = DateTime.Today.AddDays(3);
            _log4net.Info("User is in add to cart page");
            return View();
        }

        // add cart form
        [HttpPost]
        public ActionResult AddToCart(Cart productCart)
        {
            string token = HttpContext.Session.GetString("token");
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }

            var msg = repo.AddCart(token, productCart);
            

            _log4net.Info("User is adding to cart");
            if (msg == "true") { 
                
                return RedirectToAction("Index");
            }
            TempData["SuccessMessage"] = msg;
            return RedirectToAction("Index","WishList");
        }



        //edit cart
        public ActionResult EditCart(int Id)
        {
            string token = HttpContext.Session.GetString("token");
            if (HttpContext.Session.GetString("token") == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            int userid = (int)HttpContext.Session.GetInt32("userid");

            var carts = repo.GetCarts(token, userid);
            var cart = carts.SingleOrDefault(c => c.CartId == Id);

            ViewData["ProductId"] = cart.ProductId;
            ViewData["CustomerId"] = userid;
            ViewData["zipcode"] = cart.Zipcode;
            ViewData["DeliveryDate1"] = DateTime.Today.AddDays(2);
            ViewData["DeliveryDate2"] = DateTime.Today.AddDays(3);
            _log4net.Info("User is in add to cart page");
            return View();
        }

        // add cart form
        [HttpPost]
        public ActionResult EditCart(Cart productCart)
        {
            string token = HttpContext.Session.GetString("token");
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }

            var msg = repo.AddCart(token, productCart);
            TempData["SuccessMessage"] = msg;

            _log4net.Info("User is adding to cart");
            if (msg == "true")
                return RedirectToAction("Index");
            return RedirectToAction("Index", "WishList");
        }




        // GET: CartController/Details/5
        public ActionResult Checkout()
        {
            string token = HttpContext.Session.GetString("token");
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            int id = (int)HttpContext.Session.GetInt32("userid");
            repo.Checkout(token, id);

            return View("Checkout");
        }

        public ActionResult DeleteCart(int Id)
        {
            string token = HttpContext.Session.GetString("token");
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            repo.DeleteCart(token, Id);

            return RedirectToAction("Index");
        }





    }
}

E-Commerce-Portal/E-Commerce-Portal/Controllers/ECommerceController.cs
using E_Commerce_Portal.Models;
using E_Commerce_Portal.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Portal.Controllers
{
    public class ECommerceController : Controller
    {

        private readonly IRepository repo;
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ECommerceController));



        public ECommerceController(IRepository _repo)
        {

            repo = _repo;
            _log4net.Info("Logger in ECommerce");
        }


        public IActionResult Index()
        {
            List<Product> products = new List<Product>();

            string token = HttpContext.Session.GetString("token");
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            _log4net.Info("User is seeing products");

            try {
                products = repo.GetProducts(token);
            }
            catch (Exception)
            {
                _log4net.Info("Service is down");
            }
            

            return View(products);
        }

        // Search for a product
        [HttpGet]
        public IActionResult Search(int option, string productNameOrId)
        {
            string token = HttpContext.Session.GetString("token");

            List<Product> products = repo.GetProducts(token);

            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }

            if (option == 2)
            {
                _log4net.Info("User is Searching product by Id");

                if (Int32.Parse(productNameOrId) > 0)
                {
                    products = repo.GetProductsById(token, Int32.Parse(productNameOrId));
                }

                return View("Details", products);
            }

            _log4net.Info("User is Searching product by Name");

            if (!String.IsNullOrEmpty(productNameOrId))
            {
                products = repo.GetProductsByName(token, productNameOrId);
            }

            return View("Details", products);
        }

        [HttpPost]
        public IActionResult AddRating(int productId, int rate)
        {
            string token = HttpContext.Session.GetString("token");

            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            ViewBag.Id = productId;
            ViewBag.rating = rate;
            var val = repo.AddRating(token, productId, rate);

            if (val)
                return RedirectToAction("Index");
            else
                return BadRequest("Not able to add rating");
        }




    }

}

E-Commerce-Portal/E-Commerce-Portal/Views/Cart/AddToCart.cshtml
@model E_Commerce_Portal.Models.Cart

@{
    ViewData["Title"] = "AddToCart";
}

<h1>AddToCart</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddToCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="CustomerId" hidden class="control-label"></label>
                <input asp-for="CustomerId" hidden class="form-control" value="@ViewData["CustomerId"]"/>
                <span asp-validation-for="CustomerId" hidden class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" hidden class="control-label"></label>
                <input asp-for="ProductId"hidden class="form-control" value="@ViewData["ProductId"]" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" type="text" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label"></label>
                @*<input asp-for="DeliveryDate" class="form-control" />*@
            <select asp-for="DeliveryDate">
                <option value="@ViewData["DeliveryDate1"]">2 Days</option>
                <option value="@ViewData["DeliveryDate2"]">3 Days</option>
            </select>
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Item" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Commerce-Portal/E-Commerce-Portal/Views/Cart/Checkout.cshtml
@using Microsoft.AspNetCore.Http;
<div class="text-center align-content-center">
    <h2>
        @Context.Session.GetString("username") your order will be delivered to @Context.Session.GetString("address")
    </h2>
    <p>Thanks For Choosing Us !!</p>
    <p><a asp-controller="ECommerce" asp-action="Index">Buy More</a></p>
</div>



<script type="text/javascript">
            window.onbeforeunload = function () {
                window.location.href = "@Url.Action("logout", "Login")";
            };
</script>

E-Commerce-Portal/E-Commerce-Portal/Views/Cart/EditCart.cshtml
@model E_Commerce_Portal.Models.Cart

@{
    ViewData["Title"] = "AddToCart";
}

<h1>AddToCart</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CustomerId" hidden class="control-label"></label>
                <input asp-for="CustomerId" hidden class="form-control" value="@ViewData["CustomerId"]" />
                <span asp-validation-for="CustomerId" hidden class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" hidden class="control-label"></label>
                <input asp-for="ProductId" hidden class="form-control" value="@ViewData["ProductId"]" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" type="text" class="form-control" value="@ViewData["zipcode"]" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Additional Quantity</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label"></label>

                <select asp-for="DeliveryDate">
                    <option value="@ViewData["DeliveryDate1"]">2 Days</option>
                    <option value="@ViewData["DeliveryDate2"]">3 Days</option>
                </select>
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Item" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


    <script type="text/javascript">
            window.onbeforeunload = function () {
                window.location.href = "@Url.Action("logout", "Login")";
            };
    </script>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Commerce-Portal/E-Commerce-Portal/Views/Cart/Index.cshtml
@model IEnumerable<E_Commerce_Portal.ViewModel.ProductListView>

@{
    ViewData["Title"] = "Index";
}

<h1>Your Cart</h1>

<p>
    <a asp-controller="ECommerce" asp-action="Index" class="btn btn-warning">Buy More</a>
</p>
@ViewBag.Msg

@if (@ViewBag.GrandTotal > 0)
{
    <p>
        Grand Total = @ViewBag.GrandTotal
        <a data-toggle="modal" data-target="#CheckoutModal" class="btn btn-danger float-right">Checkout</a>

        <div class="modal fade" id="CheckoutModal" tabindex="-1" role="dialog" aria-labelledby="CheckoutModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content align-content-between align-items-center">

                    <div class="modal-body">
                        <h4>Are you sure ?</h4>
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>

                        <a asp-action="Checkout" class="btn btn-outline-danger ml-3">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </p>
}
<br />

<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Product Name
            </th>
            <th>
                Vendor Name
            </th>
            <th>
                Quantity
            </th>
            <th>
                Delivery Date
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@("~/image/"+item.Product.Image_Name)" asp-append-version="true" alt="Card image" height="300" width="300">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vendor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalAmount)
                </td>
                <td>
                    <a asp-action="EditCart" asp-route-Id="@item.CartId">Edit</a>
                    |
                    <a data-toggle="modal" data-target="#deleteCartModal_@item.CartId" href="#">Delete</a>

                    <div class="modal fade" id="deleteCartModal_@item.CartId" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content align-content-between align-items-center">

                                <div class="modal-body">
                                    <h4>Are you sure ?</h4>
                                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                                    <a asp-action="DeleteCart" asp-route-Id="@item.CartId" class="btn btn-outline-danger ml-3">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>


<script type="text/javascript">
            window.onbeforeunload = function () {
                window.location.href = "@Url.Action("logout", "Login")";
            };
</script>